enum Genre {
    LITTERATURE_FRANCAISE,
    LITTERATURE_JEUNESSE,
    LITTERATURE_ETRANGERE,
    POLICIER,
    POLITIQUE,
    SCIENCES,
    SCIENCES_HUMAINES,
    NON_SPECIFIER,
    ROMAN,
    CONTE,
    DYSTOPIE,
}
